### ISSUE TITLE
ReplicationDestination w/ restic should fail if a wrong encryption passphrase is detected

### ISSUE THREAD

**Issue by Ramblurr** [backube/volsync#1138] opened 2024-02-23 18:23 UTC
**Describe the bug**

If you (accidentally) set the wrong encryption passphrase and try to to a restore with a ReplicationDestination, then restic will error out with a wrong passphrase error, but the overall job completes successfully.

This is especially painful when trying to do DR with volume populator.

**Steps to reproduce**

1. Try to restore a volume using the restic data mover, but specific the wrong encryption passphrase

**Expected behavior**

The restore job should fail.

**Actual results**
The restore job completes, but no data was transferred, and if you see the restic log it complains the password was wrong.

**Additional context**

**Comment by tesshuflower** [comment] 2024-02-26 13:44
I think this is a duplicate of https://github.com/backube/volsync/pull/1005.

Please reopen if you're still having this issue with the latest code - if you're on 0.8.0, the fix should be available in the v0.9.0 release (should release in March)

**Closed** 2024-02-26 13:44 UTC
Labels: bug

**Comment by tesshuflower** [comment] 2024-02-26 15:48
Update: Actually we may be releasing a v0.8.1 in the next week or 2, which would also contain this fix.
