### ISSUE TITLE
Merge custom CA option into repository key.

### ISSUE THREAD

**Issue by blmhemu** [backube/volsync#1369] opened 2024-08-26 14:41 UTC
**Describe the feature you'd like to have.**
Currently, we need to add another customCA field if usign self signed certs.
Usually users prefer to have all the secrets in one secret resource and uniformity when using them. 

**What is the value to the end user? (why is it a priority?)**
Simplified UX - Just add `RESTIC_CUSTOM_CA` field in secret and remove `customCA` field.

**How will we know we have a good solution? (acceptance criteria)**
Listed above.

**Additional context**
NA

**Comment by tesshuflower** [comment] 2024-08-27 15:50
@blmhemu I think if the end goal is simply to use one secret, you can do this currently.

In the spec where you specify the secret, you can re-use the same secret where you store the rest of the restic config.

Say your restic secret (with keys such as `RESTIC_REPOSITORY` is called `restic-config`.

You could create a key in this `restic-config` secret that contains the contents of your ca.crt.  For this example I'll call this key `cacrtkey`.  Then you can use it in your replicationsource or replication destination like this:

```
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mydata-backup-with-customca
spec:
  restic:
    # Name of the Secret with the connection information
    repository: restic-config
    # ...
    customCA:
      secretName: restic-config
      key: cacrtkey
```

**Comment by blmhemu** [comment] 2024-08-27 18:27
While I am currently using the above approach,

It's not just about having one single secret, it's also about simplifying restic repo config. Having a standard key for CA in secret and using that instead of specifying yet another `customCA` block is a better UX from my perspective - having all restic config in one place and one yaml line.

**Comment by tesshuflower** [comment] 2024-09-03 15:41
Thanks @blmhemu .  The original implementation of customCA for restic was designed this way as the use-case was for a cert manager which creates a secret or configmap.  We can't remove this, so I think at this point because there is the workaround of putting your ca cert into the common restic secret, I'm going to close this as not planned.

**Closed** 2024-09-03 15:42 UTC
Labels: enhancement
