### ISSUE TITLE
 Implement Resource Configuration for Jobs in volsync-rsync-tls-src

### ISSUE THREAD

**Issue by Sanjeeth8733** [backube/volsync#1058] opened 2024-01-09 11:56 UTC
Currently, the volsync-rsync-tls-src jobs lack resource configuration. We propose adding configurable resource values to enhance control and optimization of resource utilization for these jobs. 

Users will benefit from improved resource management for volsync-rsync-tls-src jobs, allowing for better customization based on specific requirements. This enhancement is a priority as it enhances overall system performance and efficiency. 

 Acceptance Criteria:
 
The volsync-rsync-tls-src jobs must have configurable resource values.
Resource values should follow the specified format:

`
resources:
  requests:
    memory: <Mi>
    cpu: <m>
  limits:
    memory: <Mi>
    cpu: <m>

`
Replace <Mi> with the desired memory value and <m> with the desired CPU value.
Users can easily customize resource values to meet their specific requirements.
Additional context:

 Currently, the lack of resource configuration limits the ability to optimize performance for volsync-rsync-tls-src jobs. The proposed solution will enhance flexibility and resource utilization, contributing to overall system efficiency.

**Comment by JohnStrunk** [comment] 2024-01-09 13:53
Duplicate of #707

**Closed by JohnStrunk** 2024-01-09 13:53 UTC
Labels: duplicate, enhancement
